security:
    encoders:
        App\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        chain_provider:
            chain:
                providers: [ in_memory, app_user_provider ]
        in_memory:
            memory:
                users:
                    admin: { password: 'admin', roles: [ ROLE_ADMIN, ROLE_USER ] }
        app_user_provider:
            entity:
                class: 'App\Entity\User'
                property: 'username'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: chain_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout

    access_control:
        - { path: ^/login, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/home, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/about, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] }
